name: Build and Test - AI Journaling App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Build and test
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install backend dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: |
          cd client
          npm ci

      - name: Test backend
        run: npm run test:ci
        env:
          NODE_ENV: test

      - name: Build frontend
        run: |
          cd client
          npm run build
        env:
          CI: false
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: client/build/
          retention-days: 7

  # Simple deployment status check
  deployment-status:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Status
        run: |
          echo "✅ Build completed successfully!"
          echo "📦 Frontend build artifacts uploaded"
          echo "🚀 Ready for manual deployment to:"
          echo "   - Vercel (Frontend): https://vercel.com"
          echo "   - Railway (Backend): https://railway.app"
          echo "   - Render (Backend): https://render.com" 